(() => {
const actor=document.querySelector('#red-runner'),sprite=actor.querySelector('img'),waiter=document.querySelector('#service-waitress'),drink=document.querySelector('#service-drink'),kisses=document.querySelector('#service-kisses');
const motion=matchMedia('(prefers-reduced-motion: reduce)');let ready=false,elapsed=0,last=0,cycle=-1,entry=null,lastEdge=-1,lastPoint=null;const animations=new Set(),timers=new Set();
const lerp=(a,b,t)=>a+(b-a)*t,smooth=t=>t*t*(3-2*t),place=(el,x,y)=>el.style.transform=`translate(${x}px,${y}px)`;
function bounds(){const b=sprite.getBoundingClientRect(),ratio=sprite.naturalWidth/sprite.naturalHeight,w=Math.min(b.width,b.height*ratio),h=w/ratio;return{x:b.left+(b.width-w)/2,y:b.top+(b.height-h)/2,w,h};}
function clear(){waiter.hidden=true;drink.style.opacity=0;animations.forEach(a=>a.cancel());animations.clear();timers.forEach(clearTimeout);timers.clear();kisses.replaceChildren();cycle=-1;elapsed=0;lastPoint=null;}
function emitKiss(){const p=bounds(),el=document.createElement('span');el.className='service-kiss';el.textContent='💋';kisses.append(el);const x=p.x+p.w*.737-15,y=p.y+p.h*.313-15;const a=el.animate([{transform:`translate(${x}px,${y}px) scale(.2)`,opacity:1},{transform:`translate(${x+8}px,${y-5}px) scale(.5)`,opacity:1,offset:.14},{transform:`translate(${x+27}px,${y-22}px) scale(1)`,opacity:1,offset:.4},{transform:`translate(${x+70}px,${y-65}px) scale(.65)`,opacity:0}],{duration:950,fill:'forwards',easing:'ease-out'});animations.add(a);a.onfinish=()=>{animations.delete(a);el.remove();};}
function start(p){let edge=Math.floor(Math.random()*4);if(edge===lastEdge)edge=(edge+1+Math.floor(Math.random()*3))%4;lastEdge=edge;const w=waiter.offsetWidth,h=waiter.offsetHeight,r=.15+Math.random()*.7;const starts=[{x:-w-40,y:innerHeight*r},{x:innerWidth+40,y:innerHeight*r},{x:innerWidth*r,y:-h-40},{x:innerWidth*r,y:innerHeight+40}];entry={start:starts[edge],right:starts[edge].x<p.x,departure:null};emitKiss();const timer=setTimeout(()=>{timers.delete(timer);if(!document.hidden&&!motion.matches)emitKiss();},70);timers.add(timer);}
function draw(p){const n=Math.floor(elapsed/3000),t=elapsed%3000;waiter.hidden=false;if(n!==cycle){cycle=n;start(p);}const w=waiter.offsetWidth,h=waiter.offsetHeight,hand={x:p.x+p.w*.90,y:p.y+p.h*.55},trayX=entry.right?.8:.2,dest={x:hand.x-trayX*w+(entry.right?-19:19),y:hand.y-h*.52+9};let q;
if(t<1050){const u=smooth(t/1050);q={x:lerp(entry.start.x,dest.x,u),y:lerp(entry.start.y,dest.y,u)};}else if(t<1500){q=dest;entry.departure={...dest};}else{const from=entry.departure||dest,u=smooth(Math.min(1,(t-1500)/1150));q={x:lerp(from.x,entry.start.x,u),y:lerp(from.y,entry.start.y,u)};}
waiter.querySelector('.service-facing').style.transform=(t<1500?entry.right:!entry.right)?'':'scaleX(-1)';waiter.classList.toggle('serving',t>=1050&&t<1500);waiter.hidden=t>=2650;place(waiter,q.x,q.y);const tray={x:q.x+trayX*w,y:q.y+h*.52-8},u=Math.max(0,Math.min(1,(t-1080)/350));place(drink,lerp(tray.x,hand.x,u)-10,lerp(tray.y,hand.y,u)-Math.sin(u*Math.PI)*10-20);drink.style.opacity=t>2750?String((3000-t)/250):'1';}
function tick(now){const dt=last?Math.min(60,now-last):0;last=now;if(ready){const p=bounds(),visible=!document.hidden&&!motion.matches&&p.y+p.h>45&&p.y<innerHeight-40&&Number(getComputedStyle(actor).opacity)>.5;if(!visible){if(cycle!==-1)clear();}else{if(lastPoint&&Math.hypot(p.x-lastPoint.x,p.y-lastPoint.y)>90)clear();elapsed+=dt;draw(p);lastPoint=p;}}requestAnimationFrame(tick);}
Promise.all([sprite.decode(),waiter.querySelector('img').decode()]).then(()=>ready=true).catch(()=>clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});motion.addEventListener('change',clear);addEventListener('resize',clear);requestAnimationFrame(tick);
})();
